### ISSUE TITLE
undefined method `key?' for false:FalseClass

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/tronprint#4]
In development mode, I sometimes get

```
NoMethodError

undefined method `key?' for false:FalseClass

Rails.root: /Users/seamus/code/cm1
Application Trace | Framework Trace | Full Trace

dkastner-moneta (1.1.0) lib/moneta/adapters/yaml.rb:22:in `[]'
tronprint (1.2.0) lib/tronprint/aggregator.rb:136:in `update_entry'
tronprint (1.2.0) lib/tronprint/aggregator.rb:110:in `update_total'
tronprint (1.2.0) lib/tronprint/aggregator.rb:58:in `update'
tronprint (1.2.0) lib/tronprint/traffic_monitor.rb:22:in `increment'
tronprint (1.2.0) lib/tronprint/app.rb:10:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/head.rb:14:in `call'
rack (1.2.3) lib/rack/methodoverride.rb:24:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/flash.rb:182:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/session/abstract_store.rb:149:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/cookies.rb:302:in `call'
activerecord (3.0.9) lib/active_record/query_cache.rb:32:in `block in call'
activerecord (3.0.9) lib/active_record/connection_adapters/abstract/query_cache.rb:28:in `cache'
activerecord (3.0.9) lib/active_record/query_cache.rb:12:in `cache'
activerecord (3.0.9) lib/active_record/query_cache.rb:31:in `call'
activerecord (3.0.9) lib/active_record/connection_adapters/abstract/connection_pool.rb:354:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/callbacks.rb:46:in `block in call'
activesupport (3.0.9) lib/active_support/callbacks.rb:416:in `_run_call_callbacks'
actionpack (3.0.9) lib/action_dispatch/middleware/callbacks.rb:44:in `call'
lib/rack_xsendfile.rb:10:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/show_exceptions.rb:47:in `call'
railties (3.0.9) lib/rails/rack/logger.rb:13:in `call'
rack (1.2.3) lib/rack/runtime.rb:17:in `call'
rack (1.2.3) lib/rack/lock.rb:11:in `block in call'
<internal:prelude>:10:in `synchronize'
rack (1.2.3) lib/rack/lock.rb:11:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/static.rb:30:in `call'
railties (3.0.9) lib/rails/application.rb:168:in `call'
railties (3.0.9) lib/rails/application.rb:77:in `method_missing'
unicorn (4.0.1) lib/unicorn/http_server.rb:518:in `process_client'
unicorn (4.0.1) lib/unicorn/http_server.rb:585:in `worker_loop'
unicorn (4.0.1) lib/unicorn/http_server.rb:475:in `spawn_missing_workers'
unicorn (4.0.1) lib/unicorn/http_server.rb:135:in `start'
unicorn (4.0.1) bin/unicorn_rails:209:in `<top (required)>'
/Users/seamus/.rvm/gems/ruby-1.9.2-p180/bin/unicorn_rails:19:in `load'
/Users/seamus/.rvm/gems/ruby-1.9.2-p180/bin/unicorn_rails:19:in `<main>'
```

I don't have aggregator options set for this environment, so I assume data is being saved in <code>tronprint_stats.yml</code>.

Note that I have this at the top of my <code>config/application.rb</code> because of http://stackoverflow.com/questions/4980877/rails-error-couldnt-parse-yaml

```
require 'yaml'
YAML::ENGINE.yamler = 'syck' # <-----
require File.expand_path('../boot', __FILE__)
require 'rails/all'
Bundler.require :default, Rails.env
```

**Comment by seamusabshere** [comment]
Things start working again if I delete <code>tronprint_stats.yml</code>
